---
title: "Scrapping CSR Mangrove"
author: "Erlangga"
date: "2025-11-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# --- Load Packages ---
library(tidyRSS)
library(dplyr)
library(lubridate)
library(purrr)
library(openxlsx)

# --- Function to retrieve news by month using a query  ---
get_news_month <- function(year, month) {
  start <- sprintf("%d-%02d-01", year, month)
  end   <- sprintf("%d-%02d-%02d", year, month, days_in_month(month))
  
 query <- paste0(
    '("mangrove" AND ("CSR" OR "Corporate Social Responsibility") AND ("Kabupaten" OR "Kota") AND "bibit") ',
    'after:', start, ' before:', end
  )

  
  url <- paste0(
    "https://news.google.com/rss/search?q=",
    URLencode(query, reserved = TRUE),
    "&hl=id&gl=ID&ceid=ID:id"
  )
  
  df <- tryCatch({
    tidyfeed(url, parse_dates = TRUE) %>%
      mutate(keyword = '("mangrove" AND ("CSR" OR "Corporate Social Responsibility") AND ("Kabupaten" OR "Kota") AND "bibit")',
        year = year,
        month = month,
        pubDate = item_pub_date
      )
  }, error = function(e) {
    tibble()
  })
  
  return(df)
}

# --- Loop dari Jan 2021 up to now ---
all_news <- map_dfr(2021:year(Sys.Date()), function(y) {
  map_dfr(1:12, function(m) {
    if (y == year(Sys.Date()) && m > month(Sys.Date())) return(tibble())
    get_news_month(y, m)
  })
})

# --- Cleaning data & filter from 2021 ---
df_filtered <- all_news %>%
  filter(pubDate >= ymd("2021-01-01")) %>%
  arrange(pubDate)

# --- Saving to excel ---
write.xlsx(df_filtered, "google_news_mangrove_CSR_Fix.xlsx")

#After saving, data will be checked and cleaned manually based on criteria and duplication
```


